"""Deterministic calculation of stochastic-volatility forecast paths."""
from __future__ import annotations

from collections.abc import Mapping

import numpy as np

from .forecast_features import HAR_INPUT_MODELS, base_model_id, model_spec

SUPPORTED_MODELS = {
    "NN-SV",
    "RV-NN-SV",
    "RV-RA-NN-SV",
    "SV",
    "RV-LIN-SV",
    *HAR_INPUT_MODELS,
}


def _finite_array(
    arrays: Mapping[str, np.ndarray], name: str, *, ndim: int | None = None
) -> np.ndarray:
    if name not in arrays:
        raise ValueError(f"missing array: {name}")
    value = np.asarray(arrays[name], dtype=float)
    if ndim is not None and value.ndim != ndim:
        raise ValueError(f"{name} must be {ndim}-dimensional")
    if np.any(~np.isfinite(value)):
        raise ValueError(f"{name} contains non-finite values")
    return value


def _scalar(arrays: Mapping[str, np.ndarray], name: str) -> float:
    value = _finite_array(arrays, name)
    if value.size != 1:
        raise ValueError(f"{name} must contain one value")
    return float(value.reshape(-1)[0])


def _history(
    arrays: Mapping[str, np.ndarray], name: str, path_count: int
) -> np.ndarray:
    value = _finite_array(arrays, name)
    if value.ndim == 1 and value.size:
        return np.broadcast_to(value, (path_count, value.size)).copy()
    if value.ndim == 2 and value.shape[0] == path_count and value.shape[1]:
        return value.copy()
    raise ValueError(f"{name} must contain a nonempty history")


def _parameter_indices(
    refit: Mapping[str, np.ndarray], source_ancestry: np.ndarray
) -> np.ndarray:
    if "ancestry" not in refit:
        raise ValueError("missing array: ancestry")
    ancestry = np.asarray(refit["ancestry"], dtype=int)
    if ancestry.ndim != 1 or ancestry.size == 0:
        raise ValueError("ancestry must be a nonempty vector")
    if np.unique(ancestry).size != ancestry.size:
        raise ValueError("ancestry values must be unique")
    order = np.argsort(ancestry)
    ordered = ancestry[order]
    positions = np.searchsorted(ordered, source_ancestry)
    valid = positions < ordered.size
    if not np.all(valid) or not np.array_equal(
        ordered[positions[valid]], source_ancestry[valid]
    ):
        raise ValueError("a forecast path refers to an unavailable parameter draw")
    return order[positions]


def _selected_parameter(
    refit: Mapping[str, np.ndarray],
    name: str,
    indices: np.ndarray,
    atom_count: int,
) -> np.ndarray:
    key = f"parameter__{name}"
    value = _finite_array(refit, key)
    if value.ndim == 0 or value.shape[0] != atom_count:
        raise ValueError(f"{key} must align with ancestry")
    return value[indices]


def reconstruct_forecast_paths(
    model_id: str,
    refit: Mapping[str, np.ndarray],
    forecast_inputs: Mapping[str, np.ndarray],
) -> dict[str, np.ndarray]:
    """Reconstruct forecast paths conditional on saved stochastic inputs.

    The baseline state follows

    ``b_t = mu + phi * (b_{t-1} - mu) + eta_t``,

    and log variance is ``h_t = b_t + c_t``.  The correction ``c_t`` is a
    centred neural function for NN-SV and RV-NN-SV, the same neural function
    plus a centred residual-asymmetry term for RV-RA-NN-SV, zero for SV, and a
    centred linear function for RV-LIN-SV. ``eta_t`` and the standardized
    return innovations are supplied in ``forecast_inputs``; no random numbers
    are generated by this function.
    """
    if model_id not in SUPPORTED_MODELS:
        raise ValueError(f"unsupported model: {model_id}")
    family = base_model_id(model_id)
    har_inputs = model_id in HAR_INPUT_MODELS

    state_innovations = _finite_array(
        forecast_inputs, "state_innovations", ndim=2
    )
    return_innovations = _finite_array(
        forecast_inputs, "return_innovations", ndim=2
    )
    if state_innovations.shape != return_innovations.shape:
        raise ValueError("state and return innovations must have the same shape")
    path_count, horizon = state_innovations.shape
    if path_count == 0 or horizon == 0:
        raise ValueError("forecast inputs must contain at least one path and step")
    if (family == "RV-LIN-SV" or har_inputs) and horizon != 1:
        raise ValueError(f"{model_id} forecasts are defined for horizon one")

    origin_state = _finite_array(
        forecast_inputs, "origin_baseline_states", ndim=1
    )
    if "source_parameter_ancestry" not in forecast_inputs:
        raise ValueError("missing array: source_parameter_ancestry")
    source_ancestry = np.asarray(
        forecast_inputs["source_parameter_ancestry"], dtype=int
    )
    if origin_state.shape != (path_count,) or source_ancestry.shape != (
        path_count,
    ):
        raise ValueError("origin states and parameter ancestry must align with paths")

    indices = _parameter_indices(refit, source_ancestry)
    atom_count = np.asarray(refit["ancestry"]).size
    parameters = {
        name: _selected_parameter(refit, name, indices, atom_count)
        for name in ("mu", "phi")
    }
    if any(parameters[name].shape != (path_count,) for name in ("mu", "phi")):
        raise ValueError("state parameters must contain one value per path")
    if np.any((parameters["phi"] <= 0) | (parameters["phi"] >= 1)):
        raise ValueError("phi must lie strictly between zero and one")
    return_mean = _scalar(refit, "return_mean")
    return_scale = _scalar(refit, "return_scale")
    if return_scale <= 0:
        raise ValueError("return_scale must be positive")

    z_history: np.ndarray | None = None
    rv_history: np.ndarray | None = None
    future_log_rv: np.ndarray | None = None
    asymmetry_history: np.ndarray | None = None
    future_asymmetry: np.ndarray | None = None
    feature_mean: np.ndarray | None = None
    feature_scale: np.ndarray | None = None
    if model_id != "SV":
        z_history = _history(
            forecast_inputs, "origin_z_history_tail", path_count
        )
        dimension = len(model_spec(model_id).feature_names)
        feature_mean = _finite_array(refit, "feature_mean", ndim=1)
        feature_scale = _finite_array(refit, "feature_scale", ndim=1)
        if feature_mean.shape != (dimension,) or feature_scale.shape != (
            dimension,
        ):
            raise ValueError("feature normalization does not match the model")
        if np.any(feature_scale <= 0):
            raise ValueError("feature scales must be positive")
        if dimension >= 2:
            rv_history = _history(
                forecast_inputs, "origin_log_rv_history_tail", path_count
            )
            if har_inputs and rv_history.shape[1] < 22:
                raise ValueError("HAR forecasts require 22 observed log-OC values")
            if model_id in {"RV-NN-SV", "RV-RA-NN-SV"}:
                future_log_rv = _finite_array(
                    forecast_inputs, "future_log_rv_paths", ndim=2
                )
                if future_log_rv.shape != (path_count, horizon):
                    raise ValueError("future log-RV paths must align with forecast paths")
        if model_id == "RV-RA-NN-SV":
            asymmetry_history = _history(
                forecast_inputs, "origin_asymmetry_history_tail", path_count
            )
            future_asymmetry = _finite_array(
                forecast_inputs, "future_asymmetry_paths", ndim=2
            )
            if future_asymmetry.shape != (path_count, horizon):
                raise ValueError(
                    "future asymmetry paths must align with forecast paths"
                )

    if family in {"NN-SV", "RV-NN-SV", "RV-RA-NN-SV"}:
        parameters.update(
            {
                name: _selected_parameter(refit, name, indices, atom_count)
                for name in ("w1", "b1", "output_weights", "centering_constant")
            }
        )
        dimension = len(model_spec(model_id).feature_names) - (model_id == "RV-RA-NN-SV")
        w1 = parameters["w1"]
        b1 = parameters["b1"]
        output_weights = parameters["output_weights"]
        if w1.ndim != 3 or w1.shape[:2] != (path_count, dimension):
            raise ValueError("neural weights do not match paths and features")
        if b1.shape != (path_count, w1.shape[2]) or output_weights.shape != (
            path_count,
            w1.shape[2],
        ):
            raise ValueError("neural hidden-layer arrays do not align")
        if parameters["centering_constant"].shape != (path_count,):
            raise ValueError("neural centering constants must align with paths")
        if model_id == "RV-RA-NN-SV":
            parameters.update(
                {
                    name: _selected_parameter(refit, name, indices, atom_count)
                    for name in ("gamma_A", "q_centering_mean")
                }
            )
            if any(
                parameters[name].shape != (path_count,)
                for name in ("gamma_A", "q_centering_mean")
            ):
                raise ValueError(
                    "residual-asymmetry parameters must align with paths"
                )
    elif family == "RV-LIN-SV":
        parameters.update(
            {
                name: _selected_parameter(refit, name, indices, atom_count)
                for name in ("beta", "x_center")
            }
        )
        dimension = len(model_spec(model_id).feature_names)
        if parameters["beta"].shape != (path_count, dimension) or parameters[
            "x_center"
        ].shape != (path_count, dimension):
            raise ValueError("linear coefficients and centers must align with paths")

    output_names = (
        "baseline_states",
        "latent_states",
        "transition_means",
        "ar_components",
        "observable_corrections",
        "standardized_returns",
        "standardized_variances",
        "raw_returns",
        "raw_variances",
        "raw_return_locations",
        "raw_conditional_sds",
    )
    outputs = {
        name: np.empty((path_count, horizon), dtype=float)
        for name in output_names
    }

    state = origin_state.copy()
    for step in range(horizon):
        if model_id == "SV":
            correction = np.zeros(path_count)
        else:
            assert z_history is not None
            assert feature_mean is not None and feature_scale is not None
            raw_features = z_history[:, -1, None]
            if model_id != "NN-SV":
                assert rv_history is not None
                raw_features = np.column_stack(
                    (z_history[:, -1], rv_history[:, -1])
                )
            if model_id == "RV-RA-NN-SV":
                assert asymmetry_history is not None
                raw_features = np.column_stack(
                    (
                        z_history[:, -1],
                        rv_history[:, -1],
                        asymmetry_history[:, -1],
                    )
                )
            if har_inputs:
                raw_features = np.column_stack(
                    (z_history[:, -1], rv_history[:, -1],
                     rv_history[:, -5:].mean(axis=1), rv_history[:, -22:].mean(axis=1))
                )
            features = (raw_features - feature_mean) / feature_scale
            if family in {"NN-SV", "RV-NN-SV", "RV-RA-NN-SV"}:
                core_features = (
                    features[:, :-1]
                    if model_id == "RV-RA-NN-SV"
                    else features
                )
                hidden = np.tanh(
                    np.einsum(
                        "nd,ndh->nh", core_features, parameters["w1"]
                    )
                    + parameters["b1"]
                )
                correction = (
                    np.einsum(
                        "nh,nh->n", hidden, parameters["output_weights"]
                    )
                    - parameters["centering_constant"]
                )
                if model_id == "RV-RA-NN-SV":
                    correction += parameters["gamma_A"] * (
                        features[:, -1] - parameters["q_centering_mean"]
                    )
            else:
                correction = np.einsum(
                    "nd,nd->n",
                    features - parameters["x_center"],
                    parameters["beta"],
                )

        ar_component = parameters["phi"] * (state - parameters["mu"])
        transition_mean = parameters["mu"] + ar_component
        state = transition_mean + state_innovations[:, step]
        latent_state = state + correction
        with np.errstate(over="raise", invalid="raise"):
            standardized_variance = np.exp(latent_state)
        standardized_return = (
            np.sqrt(standardized_variance) * return_innovations[:, step]
        )
        raw_variance = return_scale**2 * standardized_variance
        raw_conditional_sd = return_scale * np.sqrt(standardized_variance)
        raw_return = return_mean + return_scale * standardized_return

        values = {
            "baseline_states": state,
            "latent_states": latent_state,
            "transition_means": transition_mean,
            "ar_components": ar_component,
            "observable_corrections": correction,
            "standardized_returns": standardized_return,
            "standardized_variances": standardized_variance,
            "raw_returns": raw_return,
            "raw_variances": raw_variance,
            "raw_return_locations": np.full(path_count, return_mean),
            "raw_conditional_sds": raw_conditional_sd,
        }
        for name, value in values.items():
            outputs[name][:, step] = value

        if z_history is not None:
            z_history = np.column_stack(
                (z_history[:, 1:], standardized_return)
            )
        if rv_history is not None and future_log_rv is not None:
            rv_history = np.column_stack(
                (rv_history[:, 1:], future_log_rv[:, step])
            )
        if asymmetry_history is not None and future_asymmetry is not None:
            asymmetry_history = np.column_stack(
                (asymmetry_history[:, 1:], future_asymmetry[:, step])
            )

    return outputs
